version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springdoc:springdoc-openapi-ui
    versions:
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: net.bull.javamelody:javamelody-spring-boot-starter
    versions:
    - 1.86.0
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - 2020.0.1
